<?php

namespace Container3jN5zrL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XL8g3YLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xL8g3YL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xL8g3YL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.Yye5Kc3', 'get_ServiceLocator_Yye5Kc3Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.QaaDzHL', 'get_ServiceLocator_QaaDzHLService', true],
            'App\\Controller\\SecurityController::resetPass' => ['privates', '.service_locator.GOeE_ve', 'get_ServiceLocator_GOeEVeService', true],
            'App\\Controller\\UserController::addUser' => ['privates', '.service_locator.6vW98AK', 'get_ServiceLocator_6vW98AKService', true],
            'App\\Controller\\UserController::deleteUser' => ['privates', '.service_locator.XhaxMWK', 'get_ServiceLocator_XhaxMWKService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.d9r6TWa', 'get_ServiceLocator_D9r6TWaService', true],
            'App\\Controller\\UserController::getAllUsers' => ['privates', '.service_locator.OjqGBDQ', 'get_ServiceLocator_OjqGBDQService', true],
            'App\\Controller\\UserController::getUsers' => ['privates', '.service_locator.OjqGBDQ', 'get_ServiceLocator_OjqGBDQService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.rSCXRnT', 'get_ServiceLocator_RSCXRnTService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.Yye5Kc3', 'get_ServiceLocator_Yye5Kc3Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.QaaDzHL', 'get_ServiceLocator_QaaDzHLService', true],
            'App\\Controller\\SecurityController:resetPass' => ['privates', '.service_locator.GOeE_ve', 'get_ServiceLocator_GOeEVeService', true],
            'App\\Controller\\UserController:addUser' => ['privates', '.service_locator.6vW98AK', 'get_ServiceLocator_6vW98AKService', true],
            'App\\Controller\\UserController:deleteUser' => ['privates', '.service_locator.XhaxMWK', 'get_ServiceLocator_XhaxMWKService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.d9r6TWa', 'get_ServiceLocator_D9r6TWaService', true],
            'App\\Controller\\UserController:getAllUsers' => ['privates', '.service_locator.OjqGBDQ', 'get_ServiceLocator_OjqGBDQService', true],
            'App\\Controller\\UserController:getUsers' => ['privates', '.service_locator.OjqGBDQ', 'get_ServiceLocator_OjqGBDQService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.rSCXRnT', 'get_ServiceLocator_RSCXRnTService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\SecurityController::forgottenPassword' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'App\\Controller\\SecurityController::resetPass' => '?',
            'App\\Controller\\UserController::addUser' => '?',
            'App\\Controller\\UserController::deleteUser' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::getAllUsers' => '?',
            'App\\Controller\\UserController::getUsers' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\SecurityController:forgottenPassword' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
            'App\\Controller\\SecurityController:resetPass' => '?',
            'App\\Controller\\UserController:addUser' => '?',
            'App\\Controller\\UserController:deleteUser' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:getAllUsers' => '?',
            'App\\Controller\\UserController:getUsers' => '?',
            'App\\Controller\\UserController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
