<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJVjKGBr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJVjKGBr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJVjKGBr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJVjKGBr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJVjKGBr\App_KernelDevDebugContainer([
    'container.build_hash' => 'JVjKGBr',
    'container.build_id' => 'fb93aea9',
    'container.build_time' => 1674422183,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJVjKGBr');
